import { Profile, Photo, Album, Comment } from "@/types";

export const DEMO_PROFILES: Profile[] = [
  {
    id: "user-1",
    username: "elena_rostova",
    display_name: "Elena Rostova",
    bio: "Visual storyteller & landscape photographer exploring the Arctic wilderness and Nordic fjords. Leica Ambassador.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    banner_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80",
    website: "https://elenarostova.photography",
    instagram: "elena.rostova",
    twitter: "elena_rostova",
    gear_list: ["Leica M11", "Summilux-M 35mm f/1.4", "Sony A7R V", "FE 24-70mm f/2.8 GM II", "Gitzo Mountaineer Tripod"],
    role: "photographer",
    photos_count: 14,
    followers_count: 1240,
    following_count: 180,
  },
  {
    id: "user-2",
    username: "marcus_chen",
    display_name: "Marcus Chen",
    bio: "Street & documentary photographer capturing the neon pulses and quiet souls of Tokyo, Hong Kong, and Seoul.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    banner_url: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1600&q=80",
    website: "https://marcuschen.studio",
    instagram: "marcus.street",
    twitter: "marcus_chen",
    gear_list: ["Fujifilm X-Pro3", "Fujinon XF 23mm f/1.4 R LM WR", "Ricoh GR III Street Edition"],
    role: "photographer",
    photos_count: 18,
    followers_count: 2890,
    following_count: 310,
  },
  {
    id: "user-3",
    username: "sophia_vance",
    display_name: "Sophia Vance",
    bio: "Fine art editorial & portrait artist. Exploring natural light, analog textures, and intimate emotional nuances.",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    banner_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=80",
    website: "https://sophiavance.art",
    instagram: "sophia.vance",
    gear_list: ["Hasselblad 907X 50C", "XCD 80mm f/1.9", "Contax T2 (35mm Film)"],
    role: "photographer",
    photos_count: 12,
    followers_count: 4510,
    following_count: 95,
  },
  {
    id: "user-admin",
    username: "admin",
    display_name: "Hub Admin",
    bio: "Photography-Hub platform curation and editorial lead.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    role: "admin",
    photos_count: 0,
    followers_count: 8500,
    following_count: 42,
  }
];

export const DEMO_PHOTOS: Photo[] = [
  {
    id: "photo-1",
    owner_id: "user-1",
    album_id: "album-1",
    title: "Nordic Solitude at First Dawn",
    storage_path: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=600&q=80",
    caption: "Early morning fog creeping across a glacial pine valley in northern Norway as the first rays of amber sunlight breach the peaks.",
    ai_tags: ["Landscape", "Morning", "Misty", "Mountains", "Nordic", "Wilderness", "Golden Hour", "Calm", "Emerald & Amber"],
    ai_description: "A breathtaking wide landscape capturing morning mist rolling between rugged mountain peaks and evergreen forests in low-angled golden sunlight.",
    ai_critique: {
      overallScore: 94,
      summary: "Exceptional atmosphere and sublime atmospheric depth. The dynamic range between the amber mist and shadowed conifers is handled with masterclass finesse.",
      composition: {
        score: 95,
        feedback: "The layers of receding ridges create strong depth cues. The gentle diagonal flow of the mist guides the viewer effortlessly through the frame.",
      },
      lighting: {
        score: 96,
        feedback: "Magnificent low-angle morning backlight illuminating the fog particles while maintaining texture in the shadowed pines.",
      },
      colorGrading: {
        score: 92,
        feedback: "Harmonious split between cold slate blues in shadows and warm amber golds in the fog highlights.",
      },
      technical: {
        score: 93,
        feedback: "Pin-sharp focus on foreground trees with clean noise control at base ISO.",
      },
      actionableTips: [
        "A micro-crop on the bottom right could eliminate the slightly bright leaf reflection.",
        "Consider subtle dodge on the mid-ground mountain face to reveal subtle rock strata.",
      ],
      recommendedAdjustments: {
        exposure: "+0.1 EV",
        highlights: "-12",
        shadows: "+8",
        temperature: "+150K",
        vibrance: "+5",
      },
    },
    exif: {
      make: "Sony",
      model: "ILCE-7RM5",
      lens: "FE 24-70mm F2.8 GM II",
      focalLength: "48mm",
      aperture: "f/8.0",
      shutterSpeed: "1/125s",
      iso: 100,
      dateTime: "2024-10-14 06:42:18",
      dimensions: { width: 4200, height: 2800 },
    },
    camera_make: "Sony",
    camera_model: "Sony A7R V",
    lens: "FE 24-70mm F2.8 GM II",
    focal_length: "48mm",
    aperture: "f/8.0",
    shutter_speed: "1/125s",
    iso: 100,
    width: 4200,
    height: 2800,
    color_palette: ["#1e293b", "#0f172a", "#f59e0b", "#78716c", "#14532d"],
    aspect_ratio: "3:2",
    category: "Landscape",
    location: "Lofoten Islands, Norway",
    is_public: true,
    price: 49,
    views_count: 1420,
    likes_count: 248,
    created_at: "2024-10-15T08:00:00Z",
    profiles: DEMO_PROFILES[0],
    is_liked: false,
    is_saved: false,
  },
  {
    id: "photo-2",
    owner_id: "user-2",
    album_id: "album-2",
    title: "Cybernetic Rain: Shibuya After Hours",
    storage_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    caption: "Reflections of neon signage on drenched asphalt as a solitary commuter navigates the midnight alleys of Shibuya.",
    ai_tags: ["Street", "Night", "Cyberpunk", "Tokyo", "Rain", "Neon", "Reflections", "Cinematic", "Moody", "Urban"],
    ai_description: "A dark, evocative street scene with vivid magenta and cyan neon lights reflecting on wet pavement around a silhouette holding an umbrella.",
    ai_critique: {
      overallScore: 91,
      summary: "Striking cinematic mood with powerful complementary neon color contrast. Captures modern urban isolation with poetic clarity.",
      composition: {
        score: 90,
        feedback: "Leading reflection lines on the asphalt draw the eye toward the center subject silhouette.",
      },
      lighting: {
        score: 93,
        feedback: "Excellent exposure control preventing neon highlights from clipping while maintaining deep rich blacks.",
      },
      colorGrading: {
        score: 94,
        feedback: "Classic Blade Runner-esque teal and orange/magenta aesthetic done with restraint.",
      },
      technical: {
        score: 87,
        feedback: "Slight motion blur on peripheral rain droplets which actually adds to the kinetic street energy.",
      },
      actionableTips: [
        "Slightly lift the dark shadow on the left wall to add subtle textural context.",
        "Add a subtle vignette to focus attention strictly onto the umbrella silhouette.",
      ],
      recommendedAdjustments: {
        exposure: "0.0 EV",
        highlights: "-18",
        shadows: "+14",
        temperature: "-200K",
        vibrance: "+10",
      },
    },
    exif: {
      make: "Fujifilm",
      model: "X-Pro3",
      lens: "XF 23mm F1.4 R LM WR",
      focalLength: "23mm (35mm equiv)",
      aperture: "f/1.4",
      shutterSpeed: "1/60s",
      iso: 800,
      dateTime: "2024-11-02 23:15:40",
      dimensions: { width: 3800, height: 2533 },
    },
    camera_make: "Fujifilm",
    camera_model: "Fujifilm X-Pro3",
    lens: "XF 23mm F1.4 R LM WR",
    focal_length: "23mm",
    aperture: "f/1.4",
    shutter_speed: "1/60s",
    iso: 800,
    width: 3800,
    height: 2533,
    color_palette: ["#09090b", "#ec4899", "#06b6d4", "#3b82f6", "#1e1b4b"],
    aspect_ratio: "3:2",
    category: "Street",
    location: "Tokyo, Japan",
    is_public: true,
    price: 39,
    views_count: 2180,
    likes_count: 412,
    created_at: "2024-11-03T12:00:00Z",
    profiles: DEMO_PROFILES[1],
    is_liked: true,
    is_saved: true,
  },
  {
    id: "photo-3",
    owner_id: "user-3",
    album_id: "album-3",
    title: "Shadows & Silk: Minimalist Studio Study",
    storage_path: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    caption: "A high-fashion portrait capturing sculptural natural window shadows across gentle facial planes and silk texture.",
    ai_tags: ["Portrait", "Fashion", "Minimalist", "Studio", "Chiaroscuro", "Monochrome", "Elegant", "Analog Feel"],
    ai_description: "An elegant, close-up fine art portrait illuminated by raking directional window light creating sculpted cheekbone highlights and deep shadows.",
    ai_critique: {
      overallScore: 96,
      summary: "Breathtaking portraiture. The tonal gradation of skin tones and tactile fabric texture evokes timeless classical painting.",
      composition: {
        score: 96,
        feedback: "Unconventional framing with intimate negative space that amplifies the subject's gaze.",
      },
      lighting: {
        score: 98,
        feedback: "Masterful Rembrandt light pattern with soft feathered falloff across the neck and collarbone.",
      },
      colorGrading: {
        score: 95,
        feedback: "Pristine muted tones with creamy highlights and non-destructive neutral skin fidelity.",
      },
      technical: {
        score: 95,
        feedback: "Medium format clarity with unmatched micro-contrast in the iris and eyelash details.",
      },
      actionableTips: [
        "Nothing to change; this is exhibition ready.",
      ],
      recommendedAdjustments: {
        exposure: "0.0 EV",
        highlights: "-5",
        shadows: "+5",
        temperature: "+50K",
        vibrance: "0",
      },
    },
    exif: {
      make: "Hasselblad",
      model: "907X 50C",
      lens: "XCD 80mm F1.9",
      focalLength: "80mm",
      aperture: "f/2.2",
      shutterSpeed: "1/200s",
      iso: 64,
      dateTime: "2024-09-20 15:10:02",
      dimensions: { width: 4500, height: 3375 },
    },
    camera_make: "Hasselblad",
    camera_model: "Hasselblad 907X",
    lens: "XCD 80mm F1.9",
    focal_length: "80mm",
    aperture: "f/2.2",
    shutter_speed: "1/200s",
    iso: 64,
    width: 4500,
    height: 3375,
    color_palette: ["#1c1917", "#e7e5e4", "#a8a29e", "#44403c", "#78716c"],
    aspect_ratio: "4:3",
    category: "Portrait",
    location: "Paris, France",
    is_public: true,
    price: 75,
    views_count: 3100,
    likes_count: 580,
    created_at: "2024-09-21T09:30:00Z",
    profiles: DEMO_PROFILES[2],
    is_liked: false,
    is_saved: false,
  },
  {
    id: "photo-4",
    owner_id: "user-1",
    album_id: "album-1",
    title: "The Silent Monolith",
    storage_path: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    caption: "Dramatic Alpine crag towering above sea of rolling low clouds bathed in alpine glow.",
    ai_tags: ["Landscape", "Mountains", "Alps", "Dramatic", "Clouds", "Peaks", "Sunset", "Majestic"],
    ai_description: "Towering sharp mountain peaks piercing through a sea of white clouds with orange and purple sunset glow on the rock summits.",
    ai_critique: {
      overallScore: 89,
      summary: "Incredible scale and geological grandeur. The cloud inversion creates a dreamlike surreal feeling.",
      composition: {
        score: 88,
        feedback: "Centered peak anchors the image strongly with balanced triangular lines.",
      },
      lighting: {
        score: 91,
        feedback: "Crisp alpenglow hitting the summit contrasting with cool shadowy clouds beneath.",
      },
      colorGrading: {
        score: 89,
        feedback: "Natural alpine palette with warm coral highlights.",
      },
      technical: {
        score: 90,
        feedback: "High dynamic range capture preserving ridge highlights.",
      },
      actionableTips: [
        "Slightly reduce contrast in the deepest crevices for softer transitions.",
      ],
      recommendedAdjustments: {
        exposure: "+0.15 EV",
        highlights: "-10",
        shadows: "+12",
        temperature: "-50K",
        vibrance: "+8",
      },
    },
    exif: {
      make: "Leica",
      model: "M11",
      lens: "Summilux-M 35mm f/1.4 ASPH",
      focalLength: "35mm",
      aperture: "f/5.6",
      shutterSpeed: "1/250s",
      iso: 64,
      dateTime: "2024-10-18 17:45:10",
      dimensions: { width: 4000, height: 2667 },
    },
    camera_make: "Leica",
    camera_model: "Leica M11",
    lens: "Summilux-M 35mm f/1.4",
    focal_length: "35mm",
    aperture: "f/5.6",
    shutter_speed: "1/250s",
    iso: 64,
    width: 4000,
    height: 2667,
    color_palette: ["#1e1b4b", "#fdba74", "#94a3b8", "#334155", "#f97316"],
    aspect_ratio: "3:2",
    category: "Landscape",
    location: "Dolomites, Italy",
    is_public: true,
    price: 55,
    views_count: 1890,
    likes_count: 320,
    created_at: "2024-10-19T14:00:00Z",
    profiles: DEMO_PROFILES[0],
    is_liked: false,
    is_saved: false,
  },
  {
    id: "photo-5",
    owner_id: "user-2",
    album_id: "album-2",
    title: "Neon Monorail: Future Metropolis",
    storage_path: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80",
    caption: "Elevated train curving through the towering skyscrapers and billboards of Hong Kong at dusk.",
    ai_tags: ["Architecture", "Urban", "Hong Kong", "Night", "Long Exposure", "Cityscape", "Futuristic"],
    ai_description: "Futuristic urban cityscape with light trails from an elevated train wrapping around gleaming glass skyscrapers.",
    ai_critique: {
      overallScore: 92,
      summary: "Superb long exposure capture that transforms city transport into fluid light ribbon geometry.",
      composition: {
        score: 93,
        feedback: "Dynamic S-curve of the track leads directly into the vertical skyscraper canyon.",
      },
      lighting: {
        score: 91,
        feedback: "Perfect blue hour timing balancing artificial skyscraper lights with natural sky luminescence.",
      },
      colorGrading: {
        score: 92,
        feedback: "Rich deep indigos and electric gold trails.",
      },
      technical: {
        score: 93,
        feedback: "Tripod stability is flawless with zero vibration in building facades.",
      },
      actionableTips: [
        "Burn the slightly blown-out billboard on the top right edge to keep focus centered.",
      ],
      recommendedAdjustments: {
        exposure: "-0.1 EV",
        highlights: "-25",
        shadows: "+6",
        temperature: "-100K",
        vibrance: "+12",
      },
    },
    exif: {
      make: "Fujifilm",
      model: "X-T5",
      lens: "XF 16-55mm F2.8 R LM WR",
      focalLength: "18mm",
      aperture: "f/11",
      shutterSpeed: "8.0s",
      iso: 125,
      dateTime: "2024-11-05 18:30:12",
      dimensions: { width: 4100, height: 2733 },
    },
    camera_make: "Fujifilm",
    camera_model: "Fujifilm X-T5",
    lens: "XF 16-55mm F2.8",
    focal_length: "18mm",
    aperture: "f/11",
    shutter_speed: "8.0s",
    iso: 125,
    width: 4100,
    height: 2733,
    color_palette: ["#0a0a0c", "#1e3a8a", "#eab308", "#6366f1", "#f43f5e"],
    aspect_ratio: "3:2",
    category: "Architecture",
    location: "Kowloon, Hong Kong",
    is_public: true,
    price: 45,
    views_count: 2430,
    likes_count: 388,
    created_at: "2024-11-06T10:00:00Z",
    profiles: DEMO_PROFILES[1],
    is_liked: false,
    is_saved: false,
  },
  {
    id: "photo-6",
    owner_id: "user-3",
    album_id: "album-3",
    title: "Ethereal Botanicals: Ferns in Mist",
    storage_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1800&q=85",
    thumbnail_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    caption: "Macro details of unfurling forest fern fronds glistening with dew under soft canopy illumination.",
    ai_tags: ["Nature", "Macro", "Botanical", "Green", "Minimalist", "Serene", "Patterns", "Forest"],
    ai_description: "Intimate botanical photograph focusing on the fractal geometry of a wild fern spiral dusted with microscopic morning water drops.",
    ai_critique: {
      overallScore: 90,
      summary: "Meditative and beautifully detailed. The natural Fibonacci spiral composition is soothing and hypnotic.",
      composition: {
        score: 92,
        feedback: "Centrally framed spiral with lush out-of-focus bokeh rendering.",
      },
      lighting: {
        score: 89,
        feedback: "Diffuse overcast forest light eliminates harsh specular glare.",
      },
      colorGrading: {
        score: 91,
        feedback: "Deep forest emeralds with delicate lime accents on the tips.",
      },
      technical: {
        score: 90,
        feedback: "Razor-thin depth of field placed precisely on the center spiral crown.",
      },
      actionableTips: [
        "Focus stacking could bring the secondary frond into crisp focus if desired.",
      ],
      recommendedAdjustments: {
        exposure: "+0.05 EV",
        highlights: "-8",
        shadows: "+10",
        temperature: "-80K",
        vibrance: "+6",
      },
    },
    exif: {
      make: "Canon",
      model: "EOS R5",
      lens: "RF 100mm F2.8L Macro IS USM",
      focalLength: "100mm",
      aperture: "f/3.2",
      shutterSpeed: "1/160s",
      iso: 200,
      dateTime: "2024-08-12 09:15:00",
      dimensions: { width: 3600, height: 2400 },
    },
    camera_make: "Canon",
    camera_model: "Canon EOS R5",
    lens: "RF 100mm F2.8L Macro",
    focal_length: "100mm",
    aperture: "f/3.2",
    shutter_speed: "1/160s",
    iso: 200,
    width: 3600,
    height: 2400,
    color_palette: ["#052e16", "#15803d", "#86efac", "#14532d", "#022c22"],
    aspect_ratio: "3:2",
    category: "Nature",
    location: "Pacific Northwest, USA",
    is_public: true,
    price: 35,
    views_count: 1120,
    likes_count: 195,
    created_at: "2024-08-13T11:20:00Z",
    profiles: DEMO_PROFILES[2],
    is_liked: false,
    is_saved: false,
  }
];

export const DEMO_ALBUMS: Album[] = [
  {
    id: "album-1",
    owner_id: "user-1",
    title: "Nordic Glacial Expanses",
    description: "Two weeks venturing beyond the Arctic Circle in Norway, Iceland, and the Svalbard Archipelago.",
    visibility: "public",
    cover_photo_id: "photo-1",
    cover_photo: DEMO_PHOTOS[0],
    category: "Landscape",
    photos_count: 6,
    created_at: "2024-10-15T08:00:00Z",
    profiles: DEMO_PROFILES[0],
  },
  {
    id: "album-2",
    owner_id: "user-2",
    title: "Neon Labyrinths: Asian Megacities",
    description: "Candid nocturnal explorations through the backstreets, noodle stalls, and rain-slicked boulevards of Tokyo and Hong Kong.",
    visibility: "public",
    cover_photo_id: "photo-2",
    cover_photo: DEMO_PHOTOS[1],
    category: "Street",
    photos_count: 8,
    created_at: "2024-11-03T12:00:00Z",
    profiles: DEMO_PROFILES[1],
  },
  {
    id: "album-3",
    owner_id: "user-3",
    title: "Silhouettes & Solitude: Fine Art Studies",
    description: "An ongoing study on human form, tactile garments, and dramatic directional daylight in studio.",
    visibility: "public",
    cover_photo_id: "photo-3",
    cover_photo: DEMO_PHOTOS[2],
    category: "Portrait",
    photos_count: 5,
    created_at: "2024-09-21T09:30:00Z",
    profiles: DEMO_PROFILES[2],
  }
];

export const DEMO_COMMENTS: Comment[] = [
  {
    id: "comm-1",
    photo_id: "photo-1",
    user_id: "user-2",
    content: "The tonal falloff in the fog is extraordinary, Elena! Did you use a circular polarizer or natural morning haze?",
    created_at: "2024-10-15T10:14:00Z",
    profile: DEMO_PROFILES[1],
  },
  {
    id: "comm-2",
    photo_id: "photo-1",
    user_id: "user-3",
    content: "Sublime depth. It feels like stepping straight into a classic Scandinavian oil painting.",
    created_at: "2024-10-15T12:30:00Z",
    profile: DEMO_PROFILES[2],
  },
  {
    id: "comm-3",
    photo_id: "photo-2",
    user_id: "user-1",
    content: "That magenta neon bounce off the wet tarmac is perfection, Marcus! Gorgeous shutter speed choice.",
    created_at: "2024-11-03T14:45:00Z",
    profile: DEMO_PROFILES[0],
  }
];
